package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.24 02:41:40 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class BuildTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi38 */
  @Test
  public void testRekisteroi38() {    // Build: 38
    Build build1 = new Build(); 
    assertEquals("From: Build line: 40", 1, build1.getBid()); 
    Build build2 = new Build(); 
    int n1 = build1.getBid(); 
    int n2 = build2.getBid(); 
    assertEquals("From: Build line: 44", n2-1, n1); 
  } // Generated by ComTest END
}