package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.23 10:57:23 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class BuilditTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaaBuild31 
   * @throws SailoException when error
   */
  @Test
  public void testLisaaBuild31() throws SailoException {    // Buildit: 31
    Buildit buildit = new Buildit(); 
    Build build1 = new Build(); 
    Build build2 = new Build(); 
    assertEquals("From: Buildit line: 36", 0, buildit.getLkm()); 
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 37", 1, buildit.getLkm()); 
    buildit.lisaaBuild(build2); assertEquals("From: Buildit line: 38", 2, buildit.getLkm()); 
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 39", 3, buildit.getLkm()); 
    assertEquals("From: Buildit line: 40", build1, buildit.anna(0)); 
    assertEquals("From: Buildit line: 41", build2, buildit.anna(1)); 
    assertEquals("From: Buildit line: 42", build1, buildit.anna(2)); 
    assertEquals("From: Buildit line: 43", false, buildit.anna(1) == build1); 
    assertEquals("From: Buildit line: 44", true, buildit.anna(0) == build1); 
    try {
    assertEquals("From: Buildit line: 45", build1, buildit.anna(3)); 
    fail("Buildit: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 46", 4, buildit.getLkm()); 
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 47", 5, buildit.getLkm()); 
  } // Generated by ComTest END
}