package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.22 12:39:01 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class BuildTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi53 */
  @Test
  public void testRekisteroi53() {    // Build: 53
    Build build1 = new Build(); 
    assertEquals("From: Build line: 55", build1.getSeuraavaBid()-1, build1.getBid()); 
    Build build2 = new Build(); 
    assertEquals("From: Build line: 57", build2.getSeuraavaBid()-1, build2.getBid()); 
    assertEquals("From: Build line: 58", build2.getBid()-1, build1.getBid()); 
    assertEquals("From: Build line: 59", "Pavillion", build1.getNimi()); 
    assertEquals("From: Build line: 60", "SneakyGank", build2.getNimi()); 
    assertEquals("From: Build line: 61", "Build, jossa k‰ytet‰‰n jokaista hahmoa jolla on luonnollista armoria", build1.getKuvaus()); 
    assertEquals("From: Build line: 62", "Lorem Ipsum", build2.getKuvaus());
  } // Generated by ComTest END
}