package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.24 23:50:39 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class BuilditTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaaBuild38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaaBuild38() throws SailoException {    // Buildit: 38
    Buildit buildit = new Buildit(); 
    Build build1 = new Build(); 
    Build build2 = new Build(); 
    assertEquals("From: Buildit line: 43", 0, buildit.getLkm()); 
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 44", 1, buildit.getLkm()); 
    buildit.lisaaBuild(build2); assertEquals("From: Buildit line: 45", 2, buildit.getLkm()); 
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 46", 3, buildit.getLkm()); 
    assertEquals("From: Buildit line: 47", build1, buildit.anna(0)); 
    assertEquals("From: Buildit line: 48", build2, buildit.anna(1)); 
    assertEquals("From: Buildit line: 49", build1, buildit.anna(2)); 
    assertEquals("From: Buildit line: 50", false, buildit.anna(1) == build1); 
    assertEquals("From: Buildit line: 51", true, buildit.anna(0) == build1); 
    try {
    assertEquals("From: Buildit line: 52", build1, buildit.anna(3)); 
    fail("Buildit: 52 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 53", 4, buildit.getLkm()); 
    buildit.lisaaBuild(build1); assertEquals("From: Buildit line: 54", 5, buildit.getLkm()); 
  } // Generated by ComTest END
}