package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.24 23:54:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class Hahmon_buildTest {



  // Generated by ComTest BEGIN
  /** testHahmon_build29 */
  @Test
  public void testHahmon_build29() {    // Hahmon_build: 29
    Hahmon_build hb1 = new Hahmon_build(1, 2); 
    Hahmon_build hb2 = new Hahmon_build(5, 13); 
    assertEquals("From: Hahmon_build line: 33", false, hb1 == hb2); 
    assertEquals("From: Hahmon_build line: 34", 1, hb1.getHid()); 
    assertEquals("From: Hahmon_build line: 35", 2, hb1.getBid()); 
    assertEquals("From: Hahmon_build line: 36", 5, hb2.getHid()); 
    assertEquals("From: Hahmon_build line: 37", 13, hb2.getBid()); 
  } // Generated by ComTest END
}