package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.24 10:06:43 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HahmoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi39 */
  @Test
  public void testRekisteroi39() {    // Hahmo: 39
    Hahmo hahmo1 = new Hahmo(); 
    assertEquals("From: Hahmo line: 41", 1, hahmo1.getTunnusNro()); 
    Hahmo hahmo2 = new Hahmo(); 
    int n1 = hahmo1.getTunnusNro(); 
    int n2 = hahmo2.getTunnusNro(); 
    assertEquals("From: Hahmo line: 45", n2-1, n1); 
  } // Generated by ComTest END
}