package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.05 21:01:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class Hahmon_buildTest {



  // Generated by ComTest BEGIN
  /** testHahmon_build27 */
  @Test
  public void testHahmon_build27() {    // Hahmon_build: 27
    Hahmon_build hb1 = new Hahmon_build(1, 2); 
    Hahmon_build hb2 = new Hahmon_build(5, 13); 
    assertEquals("From: Hahmon_build line: 31", false, hb1 == hb2); 
    assertEquals("From: Hahmon_build line: 32", 1, hb1.getHid()); 
    assertEquals("From: Hahmon_build line: 33", 2, hb1.getBid()); 
    assertEquals("From: Hahmon_build line: 34", 5, hb2.getHid()); 
    assertEquals("From: Hahmon_build line: 35", 13, hb2.getBid()); 
  } // Generated by ComTest END
}