package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.05 21:01:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HahmoTest {



  // Generated by ComTest BEGIN
  /** testHahmo176 */
  @Test
  public void testHahmo176() {    // Hahmo: 176
    Hahmo hahmo1 = new Hahmo("Kalle", 3, 5, 12, 2); 
    Hahmo hahmo2 = new Hahmo("Ville", 1, 33, 74, 100); 
    assertEquals("From: Hahmo line: 179", "Kalle", hahmo1.getNimi()); 
    assertEquals("From: Hahmo line: 180", 3, hahmo1.getVoitot()); 
    assertEquals("From: Hahmo line: 181", 5, hahmo1.getHaviot()); 
    assertEquals("From: Hahmo line: 182", 12, hahmo1.getTapot()); 
    assertEquals("From: Hahmo line: 183", 2, hahmo1.getKuolemat()); 
    assertEquals("From: Hahmo line: 184", "Ville", hahmo2.getNimi()); 
    assertEquals("From: Hahmo line: 185", 1, hahmo2.getVoitot()); 
    assertEquals("From: Hahmo line: 186", 33, hahmo2.getHaviot()); 
    assertEquals("From: Hahmo line: 187", 74, hahmo2.getTapot()); 
    assertEquals("From: Hahmo line: 188", 100, hahmo2.getKuolemat()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi228 */
  @Test
  public void testRekisteroi228() {    // Hahmo: 228
    Hahmo hahmo1 = new Hahmo(); 
    assertEquals("From: Hahmo line: 230", hahmo1.getSeuraavaHid()-1, hahmo1.getHid()); 
    Hahmo hahmo2 = new Hahmo(); 
    assertEquals("From: Hahmo line: 232", hahmo2.getSeuraavaHid()-1, hahmo2.getHid()); 
    assertEquals("From: Hahmo line: 233", hahmo2.getHid()-1, hahmo1.getHid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetStats247 */
  @Test
  public void testGetStats247() {    // Hahmo: 247
    Hahmo hahmo1 = new Hahmo("Kalle", 3, 5, 12, 2); 
    Hahmo hahmo2 = new Hahmo("Ville", 1, 33, 74, 100); 
    assertEquals("From: Hahmo line: 250", 3, hahmo1.getStats()[0]); 
    assertEquals("From: Hahmo line: 251", 5, hahmo1.getStats()[1]); 
    assertEquals("From: Hahmo line: 252", 12, hahmo1.getStats()[2]); 
    assertEquals("From: Hahmo line: 253", 2, hahmo1.getStats()[3]); 
    assertEquals("From: Hahmo line: 254", 1, hahmo2.getStats()[0]); 
    assertEquals("From: Hahmo line: 255", 33, hahmo2.getStats()[1]); 
    assertEquals("From: Hahmo line: 256", 74, hahmo2.getStats()[2]); 
    assertEquals("From: Hahmo line: 257", 100, hahmo2.getStats()[3]); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse400 */
  @Test
  public void testParse400() {    // Hahmo: 400
    Hahmo hahmo = new Hahmo(false); 
    hahmo.parse("5  | Widowmaker         |  420"); 
    assertEquals("From: Hahmo line: 403", 5, hahmo.getHid()); 
    assertEquals("From: Hahmo line: 404", true, hahmo.toString().startsWith("5|Widowmaker|420")); 
  } // Generated by ComTest END
}