package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.22 16:19:22 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HahmotTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaaHahmo29 
   * @throws SailoException when error
   */
  @Test
  public void testLisaaHahmo29() throws SailoException {    // Hahmot: 29
    Hahmot hahmot = new Hahmot(); 
    Hahmo hahmo1 = new Hahmo(), hahmo2 = new Hahmo(); 
    assertEquals("From: Hahmot line: 33", 0, hahmot.getLkm()); 
    hahmot.LisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 34", 1, hahmot.getLkm()); 
    hahmot.LisaaHahmo(hahmo2); assertEquals("From: Hahmot line: 35", 2, hahmot.getLkm()); 
    hahmot.LisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 36", 3, hahmot.getLkm()); 
    assertEquals("From: Hahmot line: 37", hahmo1, hahmot.anna(0)); 
    assertEquals("From: Hahmot line: 38", hahmo2, hahmot.anna(1)); 
    assertEquals("From: Hahmot line: 39", hahmo1, hahmot.anna(2)); 
    assertEquals("From: Hahmot line: 40", false, hahmot.anna(1) == hahmo1); 
    assertEquals("From: Hahmot line: 41", true, hahmot.anna(1) == hahmo2); 
    try {
    assertEquals("From: Hahmot line: 42", hahmo1, hahmot.anna(3)); 
    fail("Hahmot: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    hahmot.LisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 43", 4, hahmot.getLkm()); 
    hahmot.LisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 44", 5, hahmot.getLkm()); 
    hahmot.LisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 45", 6, hahmot.getLkm()); 
    hahmot.LisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 46", 7, hahmot.getLkm()); 
    hahmot.LisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 47", 8, hahmot.getLkm()); 
    try {
    hahmot.LisaaHahmo(hahmo1); 
    fail("Hahmot: 48 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}