package StatTracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import StatTracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.23 19:48:46 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HahmotTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaaHahmo38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaaHahmo38() throws SailoException {    // Hahmot: 38
    Hahmot hahmot = new Hahmot(); 
    Hahmo hahmo1 = new Hahmo(), hahmo2 = new Hahmo(); 
    assertEquals("From: Hahmot line: 42", 0, hahmot.getLkm()); 
    hahmot.lisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 43", 1, hahmot.getLkm()); 
    hahmot.lisaaHahmo(hahmo2); assertEquals("From: Hahmot line: 44", 2, hahmot.getLkm()); 
    hahmot.lisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 45", 3, hahmot.getLkm()); 
    assertEquals("From: Hahmot line: 46", hahmo1, hahmot.anna(0)); 
    assertEquals("From: Hahmot line: 47", hahmo2, hahmot.anna(1)); 
    assertEquals("From: Hahmot line: 48", hahmo1, hahmot.anna(2)); 
    assertEquals("From: Hahmot line: 49", false, hahmot.anna(1) == hahmo1); 
    assertEquals("From: Hahmot line: 50", true, hahmot.anna(1) == hahmo2); 
    try {
    assertEquals("From: Hahmot line: 51", hahmo1, hahmot.anna(3)); 
    fail("Hahmot: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    hahmot.lisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 52", 4, hahmot.getLkm()); 
    hahmot.lisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 53", 5, hahmot.getLkm()); 
    hahmot.lisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 54", 6, hahmot.getLkm()); 
    hahmot.lisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 55", 7, hahmot.getLkm()); 
    hahmot.lisaaHahmo(hahmo1); assertEquals("From: Hahmot line: 56", 8, hahmot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetOverallTilastot111 
   * @throws SailoException when error
   */
  @Test
  public void testGetOverallTilastot111() throws SailoException {    // Hahmot: 111
    Hahmot hahmot = new Hahmot(); 
    Hahmo hahmo1 = new Hahmo("Kalle", 3, 5, 12, 2); 
    Hahmo hahmo2 = new Hahmo("Ville", 1, 33, 74, 100); 
    hahmot.lisaaHahmo(hahmo1); 
    hahmot.lisaaHahmo(hahmo2); 
    int[] overall = hahmot.getOverallTilastot(); 
    assertEquals("From: Hahmot line: 119", 3 + 1, overall[0]); 
    assertEquals("From: Hahmot line: 120", 5 + 33, overall[1]); 
    assertEquals("From: Hahmot line: 121", 12 + 74, overall[2]); 
    assertEquals("From: Hahmot line: 122", 2 + 100, overall[3]); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna162 
   * @throws SailoException when error
   */
  @Test
  public void testAnna162() throws SailoException {    // Hahmot: 162
    Hahmot hahmot = new Hahmot(); 
    Hahmo hahmo1 = new Hahmo("Kalle", 3, 5, 12, 2); 
    Hahmo hahmo2 = new Hahmo("Ville", 1, 33, 74, 100); 
    hahmot.lisaaHahmo(hahmo1); 
    hahmot.lisaaHahmo(hahmo2); 
    assertEquals("From: Hahmot line: 169", hahmo1, hahmot.anna(0)); 
    assertEquals("From: Hahmot line: 170", hahmo2, hahmot.anna(1)); 
  } // Generated by ComTest END
}